import type { Product } from '../types/product.types';

export const mockProducts: Product[] = [
    {
        id: 1,
        title: 'Autumn / Spring jacket - Esprit - XS',
        price: 42.9,
        oldPrice: null,
        isNew: true,
        isReserved: true,
        category: 'Accessories',
        subCategory: 'Leather belts',
        gender: ['Women', 'Unisex'],
        color: ['Red', 'White'],
        size: ['XS', '36'],
        brand: 'Esprit',
        condition: 'New',
        shop: 'Shop Vintage',
        isSale: false,
        image: 'https://images.unsplash.com/photo-1544022613-e87ca75a784a?auto=format&fit=crop&w=600&q=80',
    },
    {
        id: 2,
        title: 'Autumn / Spring jacket - Other Brand - S',
        price: 32.9,
        oldPrice: 42.9,
        isNew: true,
        isReserved: false,
        category: 'Accessories',
        subCategory: 'Leather belts',
        gender: ['Women', 'Unisex'],
        color: ['Dark', 'Brown'],
        size: ['S', '36.5'],
        brand: 'Wrangler',
        condition: 'New',
        shop: 'Second Look',
        isSale: true,
        image: 'https://images.unsplash.com/photo-1551028719-00167b16eac5?auto=format&fit=crop&w=600&q=80',
    },
    {
        id: 3,
        title: 'Faux leather jacket - Zizzi - 44',
        price: 37.9,
        oldPrice: null,
        isNew: true,
        isReserved: false,
        category: 'Accessories',
        subCategory: 'Leather belts',
        gender: ['Women', 'Unisex'],
        color: ['Grey', 'Dark'],
        size: ['44', '36'],
        brand: 'Columbia',
        condition: 'New',
        shop: 'Urban Thrift',
        isSale: false,
        image: 'https://images.unsplash.com/photo-1520975954732-35dd22299614?auto=format&fit=crop&w=600&q=80',
    },
    {
        id: 4,
        title: 'Outdoor jacket - Torstai - 46',
        price: 22.9,
        oldPrice: null,
        isNew: true,
        isReserved: false,
        category: 'Accessories',
        subCategory: 'Leather belts',
        gender: ['Women', 'Unisex'],
        color: ['Brown', 'White'],
        size: ['46', '36.5'],
        brand: 'Wrangler',
        condition: 'New',
        shop: 'Eco Wear',
        isSale: true,
        image: 'https://images.unsplash.com/photo-1548883354-7622d03aca27?auto=format&fit=crop&w=600&q=80',
    },
    {
        id: 5,
        title: 'Bright windbreaker - Torstai - M',
        price: 29.5,
        oldPrice: 38.0,
        isNew: true,
        isReserved: false,
        category: 'Apparel',
        subCategory: 'Jackets',
        gender: ['Women'],
        color: ['Yellow', 'Green'],
        size: ['M', '38'],
        brand: 'Columbia',
        condition: 'Like New',
        shop: 'Second Look',
        isSale: true,
        image: 'https://images.unsplash.com/photo-1578932750294-f5075e85f44a?auto=format&fit=crop&w=600&q=80',
    },
    {
        id: 6,
        title: "Dark denim jacket - Levi's - L",
        price: 49.0,
        oldPrice: null,
        isNew: false,
        isReserved: false,
        category: 'Apparel',
        subCategory: 'Denim',
        gender: ['Men', 'Women'],
        color: ['Dark', 'Blue'],
        size: ['L', '40'],
        brand: 'Wrangler',
        condition: 'Good',
        shop: 'Shop Vintage',
        isSale: false,
        image: 'https://images.unsplash.com/photo-1576995853123-5a10305d93c0?auto=format&fit=crop&w=600&q=80',
    },
    {
        id: 7,
        title: 'Classic winter coat - Zara - S',
        price: 55.0,
        oldPrice: 70.0,
        isNew: false,
        isReserved: false,
        category: 'Apparel',
        subCategory: 'Coats',
        gender: ['Women', 'Men'],
        color: ['Dark', 'Black'],
        size: ['S', '36'],
        brand: 'Zara',
        condition: 'Like New',
        shop: 'Urban Thrift',
        isSale: true,
        image: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?auto=format&fit=crop&w=600&q=80',
    },
    {
        id: 8,
        title: 'Vintage blue denim jacket - Wrangler - M',
        price: 34.9,
        oldPrice: null,
        isNew: true,
        isReserved: false,
        category: 'Apparel',
        subCategory: 'Denim',
        gender: ['Men', 'Women'],
        color: ['Blue', 'White'],
        size: ['M', '36.5'],
        brand: 'Wrangler',
        condition: 'New',
        shop: 'Eco Wear',
        isSale: false,
        image: 'https://images.unsplash.com/photo-1516257984-b1b4d707412e?auto=format&fit=crop&w=600&q=80',
    },
    {
        id: 9,
        title: "Leather Belt with Vintage Buckle - Levi's",
        price: 18.0,
        oldPrice: 24.0,
        isNew: true,
        isReserved: false,
        category: 'Accessories',
        subCategory: 'Leather belts',
        gender: ['Women', 'Unisex'],
        color: ['Brown', 'Dark'],
        size: ['36', '38'],
        brand: 'Columbia',
        condition: 'New',
        shop: 'Shop Vintage',
        isSale: true,
        image: 'https://images.unsplash.com/photo-1624222247344-550fb60583dc?auto=format&fit=crop&w=600&q=80',
    },
    {
        id: 10,
        title: 'Sport Run Sneakers - Nike - 37',
        price: 64.9,
        oldPrice: null,
        isNew: false,
        isReserved: false,
        category: 'Sport',
        subCategory: 'Shoes',
        gender: ['Unisex'],
        color: ['White', 'Red'],
        size: ['36.5', '37'],
        brand: 'Nike',
        condition: 'Like New',
        shop: 'Eco Wear',
        isSale: false,
        image: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=600&q=80',
    },
    {
        id: 11,
        title: 'Casual Suede Boots - Torstai - 38',
        price: 45.0,
        oldPrice: 60.0,
        isNew: true,
        isReserved: false,
        category: 'Shoes',
        subCategory: 'Boots',
        gender: ['Women', 'Children'],
        color: ['Brown', 'Dark'],
        size: ['38', '36'],
        brand: 'Torstai',
        condition: 'New',
        shop: 'Second Look',
        isSale: true,
        image: 'https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77?auto=format&fit=crop&w=600&q=80',
    },
    {
        id: 12,
        title: 'Wool Beanie Hat - Columbia - One Size',
        price: 14.5,
        oldPrice: null,
        isNew: true,
        isReserved: false,
        category: 'Accessories',
        subCategory: 'Hats',
        gender: ['Men', 'Children'],
        color: ['Grey', 'White'],
        size: ['One Size'],
        brand: 'Columbia',
        condition: 'New',
        shop: 'Urban Thrift',
        isSale: false,
        image: 'https://images.unsplash.com/photo-1576871337622-98d48d1cf531?auto=format&fit=crop&w=600&q=80',
    },
];
